---
title: US Soil Taxonomy Preceding Taxa App
author: Andrew G. Brown
date: '2020-06-13'
slug: soil-taxonomy-preceding-taxa-app
categories:
  - R
  - shiny
tags:
  - soil taxonomy
---
Continuing on my work with the underlying structure and logic of Soil Taxonomy, I have created another derivative of my text-mined database.

https://brownag.shinyapps.io/KSTPreceding/

This Shiny app shows all taxa that precede the specified taxon in the classification "sequence" specified by the Keys to Soil Taxonomy.

This type of visualization is very relevant to the logic of the Keys, because in some ways, taxa are as much what they are, as what they are not. The "sieve" that pulls out the most dissimilar soils first can be hard to keep track of. 

The KSTLookup tool (https://brownag.shinyapps.io/KSTLookup/) shows the direct logical sequence to a specific taxon, but does not inform you which taxa you passed by on your way. 

This new app (_KSTPreceding_) fills that need for tracking the taxa that logically precede a particular taxon: providing page numbers and other information about the Keys used.

In other news, both the forward and the inverse versions of the Keys to Soil Taxonomy lookup Shiny apps have received some cosmetic/quality of life upgrades to table formatting, default number of rows, and more.
